services:
  - type: web
    name: fastapi-backend
    rootDir: backend
    runtime: python3.12
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
